{{- if .Values.networkPolicies.enabled }}
{{- if .Values.networkPolicies.cilium.enabled }}
# Default Deny for Cell A
{{- if .Values.cellA.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: default-deny-cell-a
  namespace: {{ .Values.cellA.namespace }}
  labels:
    {{- include "cell-architecture.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpointSelector: {}
  ingress:
  egress:
---
{{- end }}
# Default Deny for Cell B
{{- if .Values.cellB.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: default-deny-cell-b
  namespace: {{ .Values.cellB.namespace }}
  labels:
    {{- include "cell-architecture.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpointSelector: {}
  ingress:
  egress:
{{- end }}
{{- end }}
{{- end }}