{{- if and .Values.reactClient.enabled .Values.reactClient.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.reactClient.ingress.name }}
  namespace: {{ .Values.reactClient.namespace }}
  labels:
    app: {{ .Values.reactClient.frontend.name }}
    {{- include "cell-architecture.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.reactClient.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.reactClient.ingress.className }}
  ingressClassName: {{ .Values.reactClient.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.reactClient.ingress.hosts }}
  - {{- if .host }}
    host: {{ .host | quote }}
    {{- end }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ $.Values.reactClient.service.name }}
            port:
              number: {{ $.Values.reactClient.service.port }}
      {{- end }}
  {{- end }}
{{- end }}