name: Build All Services

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:
    inputs:
      build-cell-a:
        description: 'Build Cell A services'
        required: false
        type: boolean
        default: true
      build-cell-b:
        description: 'Build Cell B services'
        required: false
        type: boolean
        default: true
      build-react-client:
        description: 'Build React client'
        required: false
        type: boolean
        default: true

jobs:
  # Cell A Services
  build-cell-a-auth:
    if: github.event_name == 'push' || inputs.build-cell-a
    uses: ./.github/workflows/reusable-go-build.yml
    with:
      service-name: auth-svc
      service-path: cell-a-apps/auth-svc
      image-name: cell-a-auth-svc
    secrets: inherit

  build-cell-a-user:
    if: github.event_name == 'push' || inputs.build-cell-a
    uses: ./.github/workflows/reusable-go-build.yml
    with:
      service-name: user-svc
      service-path: cell-a-apps/user-svc
      image-name: cell-a-user-svc
    secrets: inherit

  build-cell-a-frontend:
    if: github.event_name == 'push' || inputs.build-cell-a
    uses: ./.github/workflows/reusable-go-build.yml
    with:
      service-name: frontend-svc
      service-path: cell-a-apps/frontend-svc
      image-name: cell-a-frontend-svc
    secrets: inherit

  # Cell B Services
  build-cell-b-analytics:
    if: github.event_name == 'push' || inputs.build-cell-b
    uses: ./.github/workflows/reusable-go-build.yml
    with:
      service-name: analytics-frontend
      service-path: cell-b-apps/analytics-frontend
      image-name: cell-b-analytics-frontend
    secrets: inherit

  build-cell-b-report:
    if: github.event_name == 'push' || inputs.build-cell-b
    uses: ./.github/workflows/reusable-go-build.yml
    with:
      service-name: report-generator
      service-path: cell-b-apps/report-generator
      image-name: cell-b-report-generator
    secrets: inherit

  # React Client
  build-react-client:
    if: github.event_name == 'push' || inputs.build-react-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: yashodperera
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: react-client
          file: react-client/Dockerfile
          push: true
          tags: |
            yashodperera/cell-architecture-react-client:latest
            yashodperera/cell-architecture-react-client:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            REACT_APP_CELL_A_URL=/api/cell-a
            REACT_APP_CELL_B_URL=/api/cell-b

  # Summary job
  build-summary:
    needs: [build-cell-a-auth, build-cell-a-user, build-cell-a-frontend, build-cell-b-analytics, build-cell-b-report, build-react-client]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Build Summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Images pushed to Docker Hub:" >> $GITHUB_STEP_SUMMARY
          echo "- yashodperera/cell-a-auth-svc:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- yashodperera/cell-a-user-svc:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- yashodperera/cell-a-frontend-svc:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- yashodperera/cell-b-analytics-frontend:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- yashodperera/cell-b-report-generator:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- yashodperera/cell-architecture-react-client:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All images are also tagged with 'latest'" >> $GITHUB_STEP_SUMMARY