name: Build React Client

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'react-client/**'
      - '.github/workflows/react-client-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'react-client/**'
      - '.github/workflows/react-client-build.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: yashodperera
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: react-client
          file: react-client/Dockerfile
          push: true
          tags: |
            yashodperera/cell-architecture-react-client:latest
            yashodperera/cell-architecture-react-client:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            REACT_APP_CELL_A_URL=/api/cell-a
            REACT_APP_CELL_B_URL=/api/cell-b

      - name: Image digest
        run: echo "Image pushed to yashodperera/cell-architecture-react-client:latest"